export default {
    
    korisnikAuth: false,
    adminAuth:false,
    userEmail: '',
    brojVinaA:0,
    brojVinaB:0,
    brojVinaC:0,
    brojVinaD:0,
    brojVinaE:0,
    brojVinaF:0,
    brojLajkovaA:0,
    brojdisLajkovaA: 0,
    sumaLajkovaA:0,
    sumadisLajkovaA: 0,
    rezervacija1: 0,
    rezervacija2: 0,
    rezervacija3: 0,
    rezervacija4: 0,
    rezervacija5: 0,
    rezervacija6: 0,
    noviBrojVinaA:0,
    korisnici:[], 
}